CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Models/SpeciesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HerczegKristofFejlabuak.Web.Models
{
    public class SpeciesViewModel
    {
        public Species  EditedSpecie { get; set; }
        public List<Species> ListOfSpecies { get; set; }

    }
}

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using HerczegKristofFejlabuak.Data;
using HerczegKristofFejlabuak.Logic;
using HerczegKristofFejlabuak.Web.Models;


namespace HerczegKristofFejlabuak.Web.Controllers
{
    public class SpeciesController : Controller
    {
        ILogic<species> logic;
        IMapper mapper;
        SpeciesViewModel vm;

        public SpeciesController()
        {
            logic = new Logic<species>();
            mapper = MapperFactory.CreateMapper();

            vm = new SpeciesViewModel();
            vm.EditedSpecie = new Species();
            var Specie = logic.GetAll();
            List<species> specie = new List<species>();
            foreach (species item in Specie)
            {
                specie.Add(item);
            }
            vm.ListOfSpecies = mapper.Map<List<Data.species>, List<Models.Species>>(specie);
        }
        private Models.Species GetSpeciesModel(string name)
        {
            species species = logic.ReadOne(name);
            return mapper.Map<Data.species, Models.Species>(species);
        }
        // GET: Species
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("SpeciesIndex", vm);
        }

        // GET: Species/Details/5
        public ActionResult Details(string id)
        {
            return View("SpeciesDetails", GetSpeciesModel(id));
        }

        
        public ActionResult Remove(string id)
        {
            try
            {
                TempData["editResult"] = "Delete ok";
                logic.Delete(id);
                
            }
            catch (Exception)
            {

                TempData["editResult"] = "Delete Fail";

            }
            return RedirectToAction("Index");
        }
        public ActionResult Edit(string id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedSpecie = GetSpeciesModel(id);
            return View("SpeciesIndex", vm);
            
           
            
        }

        [HttpPost]
        public ActionResult Edit(Species species, string editAction)
        {
            if (ModelState.IsValid && species != null)
            {
                TempData["editResult"] = "Edit Ok";
                if (editAction == "AddNew")
                {
                    logic.Create(new Data.species() { species_name = species.species_name,
                     megjelenes = species.megjelenes,
                        atlagos_meret = species.atlagos_meret,
                        cute = species.cute,
                        felfedezes = species.felfedezes,
                        genus_name = species.genus_name,
                        classification = null,
                        legnagyobb_meret = species.legnagyobb_meret,
                    });
                }
                else
                {
                    try
                    {
                        logic.Update(new Data.species()
                        {
                            species_name = species.species_name,
                            megjelenes = species.megjelenes,
                            atlagos_meret = species.atlagos_meret,
                            cute = species.cute,
                            felfedezes = species.felfedezes,
                            genus_name = species.genus_name,
                            classification = null,
                            legnagyobb_meret = species.legnagyobb_meret,
                        }, species.species_name);
                    }
                    catch (Exception)
                    {

                        TempData["editResult"] = "Edit Fail";
                    }
                }
                return RedirectToAction("Index");
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedSpecie = species;
                return View("SpeciesIndex", vm);

            }
           
        }
    }
}

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Views/Species/SpecieDetailed.cshtml
@model HerczegKristofFejlabuak.Web.Models.Species
@{
    ViewBag.Title = "SpecieDetailed";
}

<h2>SpecieDetailed</h2>
@Html.ActionLink("BackToList","Index")
<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.atlagos_meret)   </td>
        <td> @Model.atlagos_meret</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.classification)   </td>
        <td> @Model.classification</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.cute)   </td>
        <td> @Model.cute</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.felfedezes)   </td>
        <td> @Model.felfedezes</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.genus_name)   </td>
        <td> @Model.genus_name</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.legnagyobb_meret)   </td>
        <td> @Model.legnagyobb_meret</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.megjelenes)   </td>
        <td> @Model.megjelenes</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.species_name)   </td>
        <td> @Model.species_name</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Views/Species/SpeciesDetails.cshtml
@model HerczegKristofFejlabuak.Web.Models.Species
@{
    ViewBag.Title = "Details";
}
<h2>SpecieDetailed</h2>
@Html.ActionLink("BackToList", "Index")
<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.atlagos_meret)   </td>
        <td> @Model.atlagos_meret</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.classification)   </td>
        <td> @Model.classification</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.cute)   </td>
        <td> @Model.cute</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.felfedezes)   </td>
        <td> @Model.felfedezes</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.genus_name)   </td>
        <td> @Model.genus_name</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.legnagyobb_meret)   </td>
        <td> @Model.legnagyobb_meret</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.megjelenes)   </td>
        <td> @Model.megjelenes</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.species_name)   </td>
        <td> @Model.species_name</td>
    </tr>
</table>

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Views/Species/SpeciesEdit.cshtml
@model HerczegKristofFejlabuak.Web.Models.Species
@{
    ViewBag.Title = "SpeciesEdit";
}
<h2>Edit one specie</h2>

@using (Html.BeginForm("Edit", "Species"))
{
    @Html.ValidationSummary()
    @Html.AntiForgeryToken()

   
    <div class="editor-label"> @Html.LabelFor(m => m.species_name)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.species_name)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.atlagos_meret)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.atlagos_meret)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.cute)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.cute)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.felfedezes)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.felfedezes)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.genus_name)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.genus_name)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.legnagyobb_meret)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.legnagyobb_meret)</div>

    <div class="editor-label"> @Html.LabelFor(m => m.megjelenes)</div>
    <div class="editor-label"> @Html.EditorFor(m => m.megjelenes)</div>

    <input type="submit" value="SEND" />
}

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Views/Species/SpeciesIndex.cshtml
@model HerczegKristofFejlabuak.Web.Models.SpeciesViewModel
@{
    ViewBag.Title = "SpeciesIndex";
}

<h2>SpeciesIndex</h2>
<p> @TempData["editResult"]</p>
@Html.Partial("SpeciesEdit", Model.EditedSpecie)
@Html.Partial("SpeciesList", Model.ListOfSpecies)

CSHARP/OENIK_PROG3_2019_2_FF9D96/HerczegKristofFejlabuak.Web/Views/Species/SpeciesList.cshtml
@model IEnumerable< HerczegKristofFejlabuak.Web.Models.Species>


<h2>List of species</h2>


@if (Model.Count() == 0)
{
<p>No Data In Database</p>
}
else
{
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.First().species_name)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.First().genus_name)
        </th>
        <th>
            Datasheet
        </th>
        <th>
            Delete
        </th>
        <th>
            Edit
        </th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@Html.DisplayFor(m => item.species_name)</td>
    <td>@Html.DisplayFor(m => item.genus_name)</td>
    <td>@Html.DisplayFor(m => item.atlagos_meret)</td>
    <td>@Html.DisplayFor(m => item.classification)</td>
    <td>@Html.DisplayFor(m => item.cute)</td>
    <td>@Html.DisplayFor(m => item.felfedezes)</td>
    <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.species_name })</td>
    <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.species_name })</td>
    <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.species_name })</td>
</tr>



    }
</table>
}